#!/usr/bin/env bash
# A script that's going to be displaying numbers from 1 to 100.

for ((i=1; i<=100; i++))
do
  if (( i % 5 == 0 && i % 3 ==0))
  then
    echo "Fizzbuzz"
  elif ((i % 3 == 0))
  then
    echo "Fizz"
  elif ((i % 5 == 0))
  then
    echo "Buzz"
  else
    echo "$i"
  fi
done
