#!/usr/bin/env bash
# this is a script that loops from 1 to 10 and:
# displaying bad luck for the 4th loop iteration
# displaying good luck for the 8th loop iteration
# displaying Best School for the other iterations

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 3 ]
  then
    echo "bad luck"
  elif [ $index -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((index++))
done
